name: sync anti-ad from privacy-protection-tools/anti-AD

on:
  workflow_dispatch:
  push: 
    branches: [ master ]
  schedule:
    - cron:  '30 19 * * *'
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: download the ad-list
      # run: git clone --depth 1 https://github.com/privacy-protection-tools/anti-AD.git ~/temp
      run: |
        wget -q https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt
    - name: rename tile to list
      run: |
        mv -f anti-ad-surge.txt anti-ad-clash.list
    - name: Commit files
      id: commit-files
      run: |
          if [ -n "$(git status --porcelain anti-ad-clash.list)" ]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "pull newest list"
            echo "hasChange=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected"
          fi       
    - name: Push changes
      uses: ad-m/github-push-action@master
      if: ${{ steps.commit-files.outputs.hasChange == 'true' }}
      with:
        github_token: ${{ secrets.PERSON_TOKEN }}
        branch: 'main'
        repository: 'conscloud/anti-ad-clash'
